export enum UserRole {
  USER = 'USER',
  ADMIN = 'ADMIN'
}

export interface User {
  id: string;
  name: string;
  email: string;
  role: UserRole;
  joinedAt: string; // ISO String
  password?: string;
}

export enum DonationStatus {
  PENDING = 'PENDING',
  SUCCESS = 'SUCCESS',
  FAILED = 'FAILED'
}

export interface Donation {
  id: string;
  userId: string;
  userName: string; // Denormalized for easier display
  amount: number;
  currency: string;
  status: DonationStatus;
  timestamp: string; // ISO String
  transactionId?: string; // Only exists if success/failed
  impactMessage?: string; // Generated by AI
}

export interface AuthState {
  user: User | null;
  isAuthenticated: boolean;
  login: (email: string, password: string) => Promise<boolean>;
  logout: () => void;
  register: (name: string, email: string, password: string) => Promise<boolean>;
}

declare global {
  interface Window {
    Razorpay: any;
  }
}
